# Generated by Django 4.0.2 on 2022-03-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_user_calories_delete_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
