# Generated by Django 4.0.2 on 2022-03-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, default='-')),
                ('Food_price', models.DecimalField(decimal_places=2, default='-', max_digits=10)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Calories', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
