# Generated by Django 4.0.2 on 2022-03-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diet_name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('Package_price', models.IntegerField(blank=True, default=0, null=True)),
                ('Breakfast', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('calories', models.IntegerField(blank=True, default=0, null=True)),
                ('Lunch', models.CharField(max_length=200)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price1', models.IntegerField(blank=True, default=0, null=True)),
                ('calories1', models.IntegerField(blank=True, default=0, null=True)),
                ('Snack', models.CharField(max_length=200)),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price2', models.IntegerField(blank=True, default=0, null=True)),
                ('calories2', models.IntegerField(blank=True, default=0, null=True)),
                ('Dinner', models.CharField(max_length=200)),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price3', models.IntegerField(blank=True, default=0, null=True)),
                ('calories3', models.IntegerField(blank=True, default=0, null=True)),
                ('TCalories', models.IntegerField(blank=True, default=0, null=True)),
                ('Tprice', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.food')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
    ]
