# Generated by Django 4.0.2 on 2022-03-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_cart_diet_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='itemD',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.diet'),
            preserve_default=False,
        ),
    ]
