# Generated by Django 4.0.2 on 2022-03-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_cartitem_itemd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='itemD',
        ),
        migrations.CreateModel(
            name='CartItemDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.diet')),
            ],
        ),
    ]
