# Generated by Django 4.0.2 on 2022-03-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_diet_name_diet_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='Package_price',
            new_name='Food_price',
        ),
    ]
