# Generated by Django 4.0.2 on 2022-09-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_product_alter_cartitem_item_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, default='-')),
                ('Food_price', models.DecimalField(decimal_places=2, default='-', max_digits=10)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Calories', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.food'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
