# Generated by Django 4.0.2 on 2022-09-20 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_productitem_biduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='biduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
