# Generated by Django 4.0.2 on 2022-03-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_cartitem_itemd_cartitemdiet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='Diet_name',
            new_name='Food_name',
        ),
    ]
